export const defaultTheme = {
    colors: {
      "base-white": "#FFFFFF",
      "base-background": "#FAFAFA",
      "base-card": "#F3F2F2",
      "base-input": "#EDEDED",
      "base-button": "#E6E5E5",
      "base-hover": "#D7D5D5",
      "base-label": "#8D8686",
      "base-text": "#574F4D",
      "base-subtitle": "#403937",
      "base-title": "#272221",
      "base-error": "#f84747",
      "brand-purple-800": "#311B92",
      "brand-purple-200": "#BA68C8",
      "brand-purple-300": "#673AB7",
      "brand-yellow-800": "#F9A825",
      "brand-yellow-200": "#FFF59D",
      "brand-yellow-300": "#DBAC2C",
      "brand-teal-800": "#00695C",
      "brand-teal-200": "#80CBC4",
      "brand-teal-300": "#4DB6AC",
    },
    textSizes: {
      "title-title-xl": "3rem",
      "title-title-l": "2rem",
      "title-title-m": "1.5rem",
      "title-title-s": "1.2rem",
      "title-title-xs": "1.125rem",
      "text-regular-l": "1.25rem",
      "text-bold-l": "1.25rem",
      "text-regular-m": "1rem",
      "text-bold-m": "1rem",
      "text-regular-s": "0.875rem",
      "text-bold-s": "0.75rem",
      "components-tag": "0.625rem",
      "components-button-g": "0.875rem",
      "components-button-s": "0.75rem",
    },
    fonts: {
      regular: "'Roboto'",
      title: "'Baloo 2'",
    },
  };